stages:
  build:
    nodeLabel: nvm-sbt
    steps:
      - |
        set +x
        . ${NVM_DIR}/nvm.sh --no-use
        nvm install
        set -x
        export NODE_OPTIONS=--openssl-legacy-provider
        sbt test
    filesToStash:
      - '**'
  deployProd:
    nodeLabel: nvm-sbt-deployer
    steps:
      - |
        set +x
        . ${NVM_DIR}/nvm.sh --no-use
        nvm install
        set -x
        export NODE_OPTIONS=--openssl-legacy-provider
        sbt deploy
