stages:
  build:
    nodeLabel: sbt
    steps:
      - |
        sbt ++2.13.1 test
    filesToStash:
      - '**'
  deployProd:
    nodeLabel: nvm-sbt-deployer
    steps:
      - |
        set +x
        . ${NVM_DIR}/nvm.sh --no-use
        nvm install serverless
        set -x
        sbt deploy
